# Generated by Django 6.0.4 on 2026-05-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Incapacitado', 'Incapacitado'), ('Suspendido', 'Suspendido')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, choices=[('Mañana 6:00am - 2:00pm', 'Mañana 6:00am - 2:00pm'), ('Tarde 2:00pm - 10:00pm', 'Tarde 2:00pm - 10:00pm')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Supervisor', 'Supervisor')], max_length=20, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Incapacitado', 'Incapacitado'), ('Suspendido', 'Suspendido')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredientes', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad_planificada', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad_producida', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], max_length=20, null=True)),
                ('empleado_responsable', models.ForeignKey(blank=True, db_column='empleado_responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.empleado')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha_produccion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('exportacion', models.ForeignKey(blank=True, db_column='exportacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.exportacion')),
                ('produccion', models.ForeignKey(blank=True, db_column='produccion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.produccion')),
            ],
        ),
        migrations.CreateModel(
            name='EmpTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(blank=True, db_column='empleado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.empleado')),
                ('turno', models.ForeignKey(blank=True, db_column='turno_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.turno')),
            ],
        ),
        migrations.AddField(
            model_name='turno',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.usuario'),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.usuario'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.usuario'),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, db_column='empleado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.empleado')),
                ('turno', models.ForeignKey(blank=True, db_column='turno_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.turno')),
                ('asignado_por', models.ForeignKey(blank=True, db_column='asignado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.usuario')),
            ],
        ),
    ]
